apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: revent-task-api-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: revent-task-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s