trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: revent-task-api-group
- name: IMAGE_TAG
  value: "$(Build.BuildId)" 

stages:
- stage: Build
  displayName: "Build and Push Docker Image"
  jobs:
  - job: BuildAndPush
    steps:
    - task: Docker@2
      displayName: "Login to Azure Container Registry"
      inputs:
        command: login
        containerRegistry: "$(ACR_SERVICE_CONNECTION)"

    - task: Docker@2
      displayName: "Build and Push Docker Image"
      inputs:
        command: buildAndPush
        repository: "$(ACR_NAME).azurecr.io/$(IMAGE_NAME)"
        dockerfile: api/Dockerfile
        tags: "$(IMAGE_TAG)"
 
    - task: PublishBuildArtifacts@1
      displayName: "Publish Kubernetes Manifests"
      inputs:
        pathToPublish: '$(Build.SourcesDirectory)/k8s'
        artifactName: manifests

- stage: Deploy
  displayName: "Deploy to AKS"
  jobs:
  - job: DeployToK8s
    steps:
    - task: AzureCLI@2
      displayName: "Set Kubernetes Context"
      inputs:
        azureSubscription: "$(AZ_SERVICE_CONNECTION)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME)

    - task: DownloadPipelineArtifact@2
      displayName: "Download Kubernetes Manifests"
      inputs:
        artifactName: 'manifests'
        downloadPath: '$(Build.SourcesDirectory)/k8s'

    - task: KubernetesManifest@1
      displayName: "Deploy Application to AKS"
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: "$(K8S_SERVICE_ENDPOINT)"
        namespace: 'revent-task'
        manifests: |
          $(Build.SourcesDirectory)/k8s/deployment.yaml
          $(Build.SourcesDirectory)/k8s/service.yaml
        containers: "$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)"
        overrideValues: |
          env.MONGO_URI=$(MONGO_URI)

    - task: AzureCLI@2
      displayName: "Deploy Prometheus Manually"
      inputs:
        azureSubscription: "$(AZ_SERVICE_CONNECTION)"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/setup/
          kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/

    - task: KubernetesManifest@1
      displayName: "Deploy ServiceMonitor to AKS"
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: "$(K8S_SERVICE_ENDPOINT)"
        namespace: 'monitoring'
        manifests: |
          $(Build.SourcesDirectory)/k8s/prometheus/service-monitor.yaml

# # Using Helm
# - stage: Deploy
#   displayName: "Deploy to AKS"
#   jobs:
#   - job: DeployToK8s
#     steps:
#     - task: AzureCLI@2
#       displayName: "Set Kubernetes Context"
#       inputs:
#         azureSubscription: "$(AZ_SERVICE_CONNECTION)"
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           az aks get-credentials --resource-group $(RESOURCE_GROUP) --name $(CLUSTER_NAME)

#     - task: AzureCLI@2
#       displayName: "Add Prometheus Helm Repository"
#       inputs:
#         azureSubscription: "$(AZ_SERVICE_CONNECTION)"
#         scriptType: bash
#         scriptLocation: inlineScript
#         inlineScript: |
#           helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
#           helm repo update

#     - task: HelmDeploy@0
#       displayName: "Install Prometheus"
#       inputs:
#         kubernetesServiceEndpoint: "$(K8S_SERVICE_ENDPOINT)"
#         namespace: "monitoring"
#         command: "upgrade"
#         chartType: "Repository"
#         chartName: "prometheus-community/kube-prometheus-stack"
#         releaseName: "prometheus"
#         arguments: "--install --create-namespace"

#     - task: HelmDeploy@0
#       displayName: "Deploy to AKS"
#       inputs:
#         kubernetesServiceEndpoint: "$(K8S_SERVICE_ENDPOINT)"
#         namespace: "revent-task"
#         command: "upgrade"
#         chartType: "FilePath"
#         chartPath: "helm/"
#         releaseName: "revent-task-api"
#         arguments: "--install --set image.tag=$(Build.BuildId)"