apiVersion: apps/v1
kind: Deployment
metadata:
  name: revent-task-api
  namespace: revent-task
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: revent-task-api
  template:
    metadata:
      labels:
        app: revent-task-api
    spec:
      containers:
      - name: revent-task-api
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
        