apiVersion: v1
kind: Service
metadata:
  name: revent-task-api
  namespace: revent-task
spec:
  type: {{ .Values.service.type }}
  selector:
    app: revent-task-api 
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}