apiVersion: apps/v1
kind: Deployment
metadata:
  name: revent-task-api-deployment
  namespace: revent-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: revent-task-api
  template:
    metadata:
      labels:
        app: revent-task-api
    spec:
      containers:
      - name: revent-task-api
        image: reventtaskapiacr.azurecr.io/revent-task-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URI
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"