replicaCount: 3

image:
  repository: reventtaskapiacr.azurecr.io/revent-task-api
  tag: latest

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"